### ISSUE TITLE
Add `eslint-plugin-react-hooks`

### ISSUE THREAD

**Issue by jgierer12** [KidkArolis/eslint-config-healthier#2]
It would be cool to add [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks), which is the official plugin by the React team to enforce the 'rules of Hooks'. Seeing as it will be added to Create React App soon, I would like to see it in Healthier too.

This shouldn't be a breaking change, since it only applies to projects using Hooks anyways and is a relatively unopiniated enforcement of the rules that are present in the React docs too.

If you approve of this change, I will work on a PR for it.

**Comment by KidkArolis** [comment]
Yes! In general, this sounds like a good idea.

We had a little bit of discussion regarding how to best handle React stuff in healthier in general. Some here https://github.com/KidkArolis/healthier/issues/20 and here https://github.com/KidkArolis/healthier/issues/16.

I need to reread those myself, but I just want to ensure that `healthier`, just like `standard`, doesn't break in non React environments. E.g. if someone's using jsx with Preact or any other library, you shouldn't get issues flagged that are only relevant for React.

So one thing we talked about was detecting if you have react installed.

Actually, in the meantime, we can just keep this in `healthier/react` config. Maybe that's what you had in mind? So yes, let's definitely add plugin-react-hooks into `healthier/react`.

**Comment by jgierer12** [comment]
> Actually, in the meantime, we can just keep this in `healthier/react` config

Yes, that is exactly what I had in mind :+1: 

I will add it and open a PR shortly.
