### ISSUE TITLE
Switched imports for standard and react

### ISSUE THREAD

**Issue by jgierer12** [KidkArolis/eslint-config-healthier#3]
While browsing, I noticed that `index.js` imports `eslintrc-react.json` and `react.js` imports `eslintrc.json`. Shouldn't these be switched?

**Comment by KidkArolis** [comment]
You're right! Something went wrong there.

I must have never noticed, since I currently usually use `healthier` directly, which doesn't yet depend on this eslint-config-healthier.

Let's fix this.
